language: rust
# use trusty for newer openblas
dist: trusty
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libopenblas-dev
