(function() {var implementors = {};
implementors["wafer"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"wafer/errors/enum.ErrorKind.html\" title=\"enum wafer::errors::ErrorKind\">ErrorKind</a>&gt; for <a class=\"struct\" href=\"wafer/errors/struct.Error.html\" title=\"struct wafer::errors::Error\">Error</a>",synthetic:false,types:["wafer::errors::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"wafer/errors/struct.Error.html\" title=\"struct wafer::errors::Error\">Error</a>",synthetic:false,types:["wafer::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt; for <a class=\"struct\" href=\"wafer/errors/struct.Error.html\" title=\"struct wafer::errors::Error\">Error</a>",synthetic:false,types:["wafer::errors::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"enum\" href=\"wafer/errors/enum.ErrorKind.html\" title=\"enum wafer::errors::ErrorKind\">ErrorKind</a>",synthetic:false,types:["wafer::errors::ErrorKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt; for <a class=\"enum\" href=\"wafer/errors/enum.ErrorKind.html\" title=\"enum wafer::errors::ErrorKind\">ErrorKind</a>",synthetic:false,types:["wafer::errors::ErrorKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"wafer/errors/struct.Error.html\" title=\"struct wafer::errors::Error\">Error</a>&gt; for <a class=\"enum\" href=\"wafer/errors/enum.ErrorKind.html\" title=\"enum wafer::errors::ErrorKind\">ErrorKind</a>",synthetic:false,types:["wafer::errors::ErrorKind"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
