(function() {var implementors = {};
implementors["wafer"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"wafer/config/enum.PotentialType.html\" title=\"enum wafer::config::PotentialType\">PotentialType</a>",synthetic:false,types:["wafer::config::PotentialType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"wafer/config/enum.InitialCondition.html\" title=\"enum wafer::config::InitialCondition\">InitialCondition</a>",synthetic:false,types:["wafer::config::InitialCondition"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"wafer/config/enum.SymmetryConstraint.html\" title=\"enum wafer::config::SymmetryConstraint\">SymmetryConstraint</a>",synthetic:false,types:[]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"wafer/config/enum.CentralDifference.html\" title=\"enum wafer::config::CentralDifference\">CentralDifference</a>",synthetic:false,types:["wafer::config::CentralDifference"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"wafer/config/enum.FileType.html\" title=\"enum wafer::config::FileType\">FileType</a>",synthetic:false,types:["wafer::config::FileType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"wafer/errors/struct.Error.html\" title=\"struct wafer::errors::Error\">Error</a>",synthetic:false,types:["wafer::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"wafer/errors/enum.ErrorKind.html\" title=\"enum wafer::errors::ErrorKind\">ErrorKind</a>",synthetic:false,types:["wafer::errors::ErrorKind"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
